OPP: Handle various crashes while sharing images through G photos.
Use case:
1. Pair with specific remote with DUT.
2. Have at least one video saved on G Photos (Cloud).
3. Select a video from Photos

Failure Logs:
 AndroidRuntime: FATAL EXCEPTION: Thread-16
 AndroidRuntime: Process: com.android.bluetooth, PID: 20950
 AndroidRuntime: java.lang.NullPointerException
 AndroidRuntime: at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
 AndroidRuntime: at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
 AndroidRuntime: at android.content.ContentResolver.query(ContentResolver.java:532)
 AndroidRuntime: at com.android.bluetooth.opp.BluetoothOppSendFileInfo.generateFileInfo
         (BluetoothOppSendFileInfo.java:115)
 AndroidRuntime: at com.android.bluetooth.opp.BluetoothOppManager.saveSendingFileInfo
         (BluetoothOppManager.java:258)

Root cause:
While Sharing video which was saved in cloud (G photos) android framework is
not able to get video info because of G Photos default Behaviour.

Fix:
Catch NPE while generating file info to avoid crash in Profile.
Change-Id: If261c9fb91925d6b9447b71e6915b4962355fc5b

Use case:
1) Open photos app
2) Open the 10MB image file
3) Click on share->Bluetooth
4) Select large size option
5) Immediately press the back key

Failure Logs:
java.lang.IllegalStateException: Can't compress a recycled bitmap
at android.os.Parcel.readException(Parcel.java:1692)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel
   (DatabaseUtils.java:146)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1147)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:984)
at com.android.bluetooth.opp.BluetoothOppSendFileInfo.generateFileInfo
   (BluetoothOppSendFileInfo.java:169)
at com.android.bluetooth.opp.BluetoothOppManager.saveSendingFileInfo
   (BluetoothOppManager.java:274)
at com.android.bluetooth.opp.BluetoothOppLauncherActivity$3.run
   (BluetoothOppLauncherActivity.java:170)
at java.lang.Thread.run(Thread.java:761)

Fix:
Catch IllegalStateException while generating file info to avoid crash in Profile.

CRs-Fixed: 2130692
Change-Id: I76bdb5e23deba276d77b6f7a697a499685e2b439