OPP: Prevent abnormal behaviour  during BT off 1) Receive file from NFC 2) During file receive turn of BT
logs:
AndroidRuntime: FATAL EXCEPTION: Bluetooth Share Service
AndroidRuntime: Process: com.android.bluetooth, PID: 2972
AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 3, Size: 0
AndroidRuntime: at java.util.ArrayList.get(ArrayList.java:437)
AndroidRuntime: at com.android.bluetooth.opp.BluetoothOppService.shouldScanFile
 (BluetoothOppService.java:983)
AndroidRuntime: at com.android.bluetooth.opp.BluetoothOppService.-wrap2(Unknown Source:0)
AndroidRuntime: at com.android.bluetooth.opp.BluetoothOppService$UpdateThread.
run(BluetoothOppService.java:589)

Root cause:
Before stopping update thread, received onDestroye API
from adapter service which is leading to Index out of bounds exception.

Fix:
Do batch clear after stop update thread, to avoid abnormal behaviour
in opp profile and use intent with extra values instead of adapter instance

OPP: Handle IllegalArgumentException during open inboud share

java.lang.IllegalArgumentException: Failed to find configured root that contains
           /storage/6663-3361/Bluetooth/Order.htm
    at android.support.v4.content.FileProvider$SimplePathStrategy.
	    getUriForFile(FileProvider.java:712)
    at android.support.v4.content.FileProvider.
	    getUriForFile(FileProvider.java:401)
Change-Id: I7ce7ee0b3b3208ce9bcef532008746ff13ebb2a0

CRs-Fixed: 2223172
Change-Id: I1f49a942ce890f427bd012e5a700d5701d9571fe