PAN: Fix potential NPE while PAN disconnection.
Use Case:
1. During monkey test.

Failure Logs:
PanService: handlePanDeviceStateChange preState: 0 state: 2
PanService: handlePanDeviceStateChange BT tethering is off/Local role is PANU drop the connection
BluetoothAdapterState: Bluetooth adapter state changed: 15-> 16
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String
 android.bluetooth.BluetoothDevice.getAddress()' on a null object reference
at com.android.bluetooth.pan.PanService.handlePanDeviceStateChange(PanService.java:888)

Root Cause:
In Some conditions, Remote Bluetooth device instance is remains null
because of PAN disconnection.

Fix:
Before fetching remote device address check BT Remote Device
instance Value to avoid NPE.

CRs-Fixed: 2128607
Change-Id: I01773b657b50392f99004d98dabf21f9704822b5